vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        participant_images:
            uri_prefix: /images/participant
            upload_destination: '%kernel.project_dir%/public/images/participant'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
